version: '3.8'

services:
  invenotry-backend:
    build: .
    container_name: invenotry-backend
    environment:
      # SQLite database file path
      DATABASE_FILENAME: .tmp/data.db
      HOST: 0.0.0.0
      PORT: 1337
    ports:
     - 1337:1337